theme = "kanagawa"

[editor]
line-number = "relative"
auto-format = true
true-color = true
search.smart-case = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline" 

[keys.insert]
j = { k = "normal_mode" }

# for the following 4 lines please see:
# https://github.com/helix-editor/helix/issues/1630
[keys.normal.g]
l = ["collapse_selection", "extend_to_line_end"]
h = ["collapse_selection", "extend_to_line_start"]
s = ["collapse_selection", "select_mode", "goto_first_nonwhitespace", "exit_select_mode"]

