[[language]]
name = "python"
auto-format = true

### lsp-ai new

[language-server.lsp-ai]
command = "lsp-ai"
args = [ "--use-seperate-log-file", "--config", "/home/sam/dotfiles/lsp-ai.config.json" ]


# [language-server.lsp-ai.config.memory]
# file_store = { }

# [language-server.lsp-ai.config.models.mistral]
# type = "mistral_fim"
# fim_endpoint = "https://codestral.mistral.ai/v1/fim/completions"
# model = "codestral-latest"
# auth_token_env_var_name = "MISTRAL_API_KEY"

# [language-server.lsp-ai.config.models.model1]
# type = "ollama"
# # model = "deepseek-coder-v2"
# model = "codegemma:7b"
# chat_endpoint = "http://192.168.2.52:11434/api/chat"
# generate_endpoint = "http://192.168.2.52:11434/api/generate"

# [language-server.lsp-ai.config.completion]
# model = "model1"

#   [language-server.lsp-ai.config.completion.parameters]
#   max_context = 1_800
#   system = """
# Instructions:
# - You are an AI programming assistant.
# - Given a piece of code with the cursor location marked by "<CURSOR>", replace "<CURSOR>" with the correct code or comment.
# - First, think step-by-step.
# - Describe your plan for what to build in pseudocode, written out in great detail.
# - Then output the code replacing the "<CURSOR>"
# - Ensure that your completion fits within the language context of the provided code snippet (e.g., Python, JavaScript, Rust, Go).

# Rules:
# - Only respond with code or comments.
# - Only replace "<CURSOR>"; do not include any previously written code.
# - Never include "<CURSOR>" in your response
# - If the cursor is within a comment, complete the comment meaningfully.
# - Handle ambiguous cases by providing the most contextually appropriate completion.
# - Be consistent with your responses."""

#     [language-server.lsp-ai.config.completion.parameters.options]
#     num_predict = 32

#     [[language-server.lsp-ai.config.completion.parameters.messages]]
#     role = "user"
#     content = "{CODE}"

# [[language-server.lsp-ai.config.actions]]
# action_display_name = "Complete"
# model = "model1"

#   [language-server.lsp-ai.config.actions.parameters]
#   max_context = 2_048
#   max_tokens = 2_048
#   # options = { num_predict = 32 }
#   system = """
# You are an AI coding assistant. Your task is to complete code snippets. The user's cursor position is marked by "<CURSOR>". Follow these steps:

# 1. Analyze the code context and the cursor position.
# 2. Provide your chain of thought reasoning, wrapped in <reasoning> tags. Include thoughts about the cursor position, what needs to be completed, and any necessary formatting.
# 3. Determine the appropriate code to complete the current thought, including finishing partial words or lines.
# 4. Replace "<CURSOR>" with the necessary code, ensuring proper formatting and line breaks.
# 5. Wrap your code solution in <answer> tags.

# Your response should always include both the reasoning and the answer. Pay special attention to completing partial words or lines before adding new lines of code.

# <examples>
# <example>
# User input:
# --main.py--
# # A function that reads in user inpu<CURSOR>t

# Response:
# <reasoning>
# 1. The cursor is positioned after "inpu" in a comment describing a function that reads user input.
# 2. We need to complete the word "input" in the comment first.
# 3. After completing the comment, we should add a new line before defining the function.
# 4. The function should use Python's built-in `input()` function to read user input.
# 5. We'll name the function descriptively and include a return statement.
# </reasoning>

# <answer>t
# def read_user_input():
#     user_input = input("Enter your input: ")
#     return user_input
# </answer>
# </example>

# <example>
# User input:
# --main.py--
# def fibonacci(n):
#     if n <= 1:
#         return n
#     else:
#         re<CURSOR>


# Response:
# <reasoning>
# 1. The cursor is positioned after "re" in the 'else' clause of a recursive Fibonacci function.
# 2. We need to complete the return statement for the recursive case.
# 3. The "re" already present likely stands for "return", so we'll continue from there.
# 4. The Fibonacci sequence is the sum of the two preceding numbers.
# 5. We should return the sum of fibonacci(n-1) and fibonacci(n-2).
# </reasoning>

# <answer>turn fibonacci(n-1) + fibonacci(n-2)</answer>
# </example>
# </examples>"""

#     [[language-server.lsp-ai.config.actions.parameters.messages]]
#     role = "user"
#     content = "{CODE}"

#   [language-server.lsp-ai.config.actions.post_process]
#   extractor = "(?s)<answer>(.*?)</answer>"


# ## lsp-ai actions

# [[language-server.lsp-ai.config.actions]]
# action_display_name = "Refactor"
# model = "model1"

#   [language-server.lsp-ai.config.actions.parameters]
#   max_context = 4_096
#   max_tokens = 4_096
#   system = """
# You are an AI coding assistant specializing in code refactoring. Your task is to analyze the given code snippet and provide a refactored version. Follow these steps:

# 1. Analyze the code context and structure.
# 2. Identify areas for improvement, such as code efficiency, readability, or adherence to best practices.
# 3. Provide your chain of thought reasoning, wrapped in <reasoning> tags. Include your analysis of the current code and explain your refactoring decisions.
# 4. Rewrite the entire code snippet with your refactoring applied.
# 5. Wrap your refactored code solution in <answer> tags.

# Your response should always include both the reasoning and the refactored code.

# <examples>
# <example>
# User input:
# def calculate_total(items):
#     total = 0
#     for item in items:
#         total = total + item['price'] * item['quantity']
#     return total


# Response:
# <reasoning>
# 1. The function calculates the total cost of items based on price and quantity.
# 2. We can improve readability and efficiency by:
#    a. Using a more descriptive variable name for the total.
#    b. Utilizing the sum() function with a generator expression.
#    c. Using augmented assignment (+=) if we keep the for loop.
# 3. We'll implement the sum() function approach for conciseness.
# 4. We'll add a type hint for better code documentation.
# </reasoning>
# <answer>
# from typing import List, Dict

# def calculate_total(items: List[Dict[str, float]]) -> float:
#     return sum(item['price'] * item['quantity'] for item in items)
# </answer>
# </example>

# <example>
# User input:
# def is_prime(n):
#     if n < 2:
#         return False
#     for i in range(2, n):
#         if n % i == 0:
#             return False
#     return True


# Response:
# <reasoning>
# 1. This function checks if a number is prime, but it's not efficient for large numbers.
# 2. We can improve it by:
#    a. Adding an early return for 2, the only even prime number.
#    b. Checking only odd numbers up to the square root of n.
#    c. Using a more efficient range (start at 3, step by 2).
# 3. We'll also add a type hint for better documentation.
# 4. The refactored version will be more efficient for larger numbers.
# </reasoning>
# <answer>
# import math

# def is_prime(n: int) -> bool:
#     if n < 2:
#         return False
#     if n == 2:
#         return True
#     if n % 2 == 0:
#         return False
    
#     for i in range(3, int(math.sqrt(n)) + 1, 2):
#         if n % i == 0:
#             return False
#     return True
# </answer>
# </example>
# </examples>"""

#     [[language-server.lsp-ai.config.actions.parameters.messages]]
#     role = "user"
#     content = "{SELECTED_TEXT}"

#   [language-server.lsp-ai.config.actions.post_process]
#   extractor = "(?s)<answer>(.*?)</answer>"

# END OF NEW TEST

# lsp-ai
# [language-server.lsp-ai]
# command = "lsp-ai"

# [language-server.lsp-ai.config.memory]
# file_store = {}

# [language-server.lsp-ai.config.models.model1]
# type = "ollama"
# model = "deepseek-coder-v2"
# # model = "qwen2.5-coder:7b"
# chat_endpoint = "http://192.168.2.5:11434/api/chat"
# generate_endpoint = "http://192.168.2.5:11434/api/generate"

# [language-server.lsp-ai.config.models.model2]
# type = "mistral_fim"
# fim_endpoint = "https://codestral.mistral.ai/v1/fim/completions"
# model = "codestral-latest"
# auth_token_env_var_name = "MISTRAL_API_KEY"

# [language-server.lsp-ai.config.completion]
# model = "model1"
# [language-server.lsp-ai.config.completion.parameters]
# max_tokens = 32
# max_context = 1024

# [language-server.lsp-ai.config.completion.parameters.options]
# num_predict = 32

# [[language-server.lsp-ai.config.chat]]
# trigger = "!C"
# action_display_name = "Chat"
# model = "model2"

# [language-server.lsp-ai.config.chat.parameters]
# max_context = 4096
# max_tokens = 1024
# system = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately"

# [language-server.lsp-ai.config.completion]
# model = "model1"
# parameters = { fim = { start = "<｜fim_begin｜>", middle = "<｜fim_hole｜>", end = "<｜fim_end｜>" }, max_context = 2000, options = { num_predict = 32 } }
# model = "model2"
# parameters = { fim = { start = "<｜fim_begin｜>", middle = "<｜fim_hole｜>", end = "<｜fim_end｜>" }, max_context = 2000, options = { num_predict = 32 } }

# [[language-server.lsp-ai.config.actions]]
#   action_display_name = "Complete"
#   model = "model1"

#   [language-server.lsp-ai.config.actions.parameters]
#     max_context = 4096
#     max_tokens = 4096
#     system = """
#       You are an AI coding assistant. Your task is to complete code snippets. The user's cursor position is marked by "". Follow these steps:

#       1. Analyze the code context and the cursor position.
#       2. Provide your chain of thought reasoning, wrapped in . Include thoughts about the cursor position, what needs to be completed, and any necessary formatting.
#       3. Determine the appropriate code to complete the current thought, including finishing partial words or lines.
#       4. Replace "" with the necessary code, ensuring proper formatting and line breaks.
#       5. Wrap your code solution in tags.

#       Your response should always include both the reasoning and the answer. Pay special attention to completing partial words or lines before adding new lines of code.
#     """

#   [language-server.lsp-ai.config.actions.messages]
#     [language-server.lsp-ai.config.actions.messages.0]
#       role = "user"
#       content = "{CODE}"

#   [language-server.lsp-ai.config.actions.post_process]
#     extractor = "(?s)(.*?)"

# [[language-server.lsp-ai.config.actions]]
# action_display_name = "Complete"
# model = "model1"
# parameters = { max_context = 4096, max_tokens = 4096, system = "You are an AI coding assistant. Your task is to complete code snippets. The user's cursor position is marked by \"<CURSOR>\". Follow these steps:\n\n1. Analyze the code context and the cursor position.\n2. Provide your chain of thought reasoning, wrapped in <reasoning> tags. Include thoughts about the cursor position, what needs to be completed, and any necessary formatting.\n3. Determine the appropriate code to complete the current thought, including finishing partial words or lines.\n4. Replace \"<CURSOR>\" with the necessary code, ensuring proper formatting and line breaks.\n5. Wrap your code solution in <answer> tags.\n\nYour response should always include both the reasoning and the answer. Pay special attention to completing partial words or lines before adding new lines of code.\n\n<examples>\n<example>\nUser input:\n--main.py--\n# A function that reads in user inpu<CURSOR>\n\nResponse:\n<reasoning>\n1. The cursor is positioned after \"inpu\" in a comment describing a function that reads user input.\n2. We need to complete the word \"input\" in the comment first.\n3. After completing the comment, we should add a new line before defining the function.\n4. The function should use Python's built-in `input()` function to read user input.\n5. We'll name the function descriptively and include a return statement.\n</reasoning>\n\n<answer>t\ndef read_user_input():\n    user_input = input(\"Enter your input: \")\n    return user_input\n</answer>\n</example>\n\n<example>\nUser input:\n--main.py--\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        re<CURSOR>\n\n\nResponse:\n<reasoning>\n1. The cursor is positioned after \"re\" in the 'else' clause of a recursive Fibonacci function.\n2. We need to complete the return statement for the recursive case.\n3. The \"re\" already present likely stands for \"return\", so we'll continue from there.\n4. The Fibonacci sequence is the sum of the two preceding numbers.\n5. We should return the sum of fibonacci(n-1) and fibonacci(n-2).\n</reasoning>\n\n<answer>turn fibonacci(n-1) + fibonacci(n-2)</answer>\n</example>\n</examples>", messages = [ {role = "user", content = "{CODE}" } ] }
# post_process = { extractor = "(?s)<answer>(.*?)</answer>" }

# introduce new langauge for buffer & snippets
[language-server.scls]
command = "simple-completion-language-server"

[language-server.omnisharp]
command = "omnisharp"
args = ["--languageserver"]

[language-server.scls.config]
max_completion_items = 7
snippets_first = true
feature_words = true
feature_snippets = true
feature_unicode_input = true
feature_paths = true

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = false, "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = false, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }

# [language-server-gopls.config]
# config = { "gofumpt" = false, "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = false, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }


[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"
config = { "disable" = ["gofumpt"] }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

# tailwind support for gomponents
[language-server.tailwindcss-ls.config.tailwindCSS]
experimental = { classRegex =  [ "Class\\(\"([^\"]*)\"\\)" ] }
includeLanguages = { go = "go" }

[language-server.mdpls]
command = "mdpls"
config ={markdown.preview.auto = true, markdown.preview.browser = "firefox" }

[[language]]
name = "make"
language-servers = ["scls"]

[[language]]
name = "go"
formatter = { command = "goimports"}
language-servers = ["gopls", "golangci-lint-lsp", "scls", "tailwindcss-ls", "lsp-ai"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "sql"
language-servers = ["scls"]

[[language]]
name = "markdown"
language-servers = ["marksman", "lsp-ai", "mdpls"]
