[[language]]
name = "python"
auto-format = true

# introduce new langauge for buffer & snippets
[language-server.scls]
command = "simple-completion-language-server"

[language-server.omnisharp]
command = "omnisharp"
args = ["--languageserver"]

[language-server.scls.config]
max_completion_items = 20
snippets_first = true
feature_words = true
feature_snippets = true
feature_unicode_input = true
feature_paths = true

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true, "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = false, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[[language]]
name = "make"
language-servers = ["scls"]

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp", "scls"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]
