# [colors.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"
#
# [colors.normal]
# black = "0x282828"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0xa89984"
# yellow = "0xd79921"
#
# [colors.primary]
# background = "0x282828"
# foreground = "0xebdbb2"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = '1.0'

[font]
size = 14.0

[font.normal]
family = "Iosevka Light Extended"
# family = "Fira Code"
# family = "Caskaydia Cove Nerd Font Mono"
# family = "Maple Mono"
style = "light"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[scrolling]
multiplier = 3

[general]
import = [
  "~/.config/alacritty/kanagawa_wave.toml"
]
