#! /bin/zsh
# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

if [ "$HOST" = "lenovo-artix" ]
then
# if on the laptop
if [ "$HOST" = "lenovo-artix" ]
then
	bspc monitor eDP -d 1 2 3 4 7 8 9 0
	polybar lenovo > /dev/null 2>&1 & disown
	(sleep 5 && ~/dotfiles/scripts/hideIt.sh --name '^polybar-lenovo_eDP' --direction top --signal --steps 0.5 > /dev/null 2>&1 & disown) & disown
else
	echo "$HOST"
	# set up multi-monitor
	# (have to change this in order to use with polybar)
	

	# bspc monitor HDMI-A-0 -d 1 2 3 4 7 8 9 0
	# bspc config -m HDMI-A-0 top_padding 30
	# TOP_MONITOR=HDMI-A-0 polybar top &

	 bspc monitor DisplayPort-1 -n bottom
	
	 bspc monitor bottom -d 1 2 3 4
	 bspc monitor DisplayPort-2 -d 7 8 9 0
	
	 # start polybars
	 polybar bottom > /dev/null 2>&1 & disown
	 polybar top > /dev/null 2>&1 & disown
	 (sleep 5 && ~/dotfiles/scripts/hideIt.sh --name '^polybar-bottom' --direction top --signal --steps 0.5 > /dev/null 2>&1 & disown) & disown
	 (sleep 5 && ~/dotfiles/scripts/hideIt.sh --name '^polybar-top' --direction top --signal --steps 0.5 > /dev/null 2>&1 & disown) & disown
	 (sleep 5 && ~/dotfiles/scripts/hideIt.sh --name 'Polybar tray window' --direction top --signal --steps 0.5 > /dev/null 2>&1 & disown) & disown
	
fi

 # padding 
bspc config top_padding 5
bspc config bottom_padding 5
bspc config right_padding 5
bspc config left_padding 5

# ensure polybar appears above other windows
(sleep 10 && xdo raise -N Polybar) & disown
(sleep 10 && xdo raise -a 'Polybar tray window') & disown

# floating window rules
bspc rule -a zoom state=floating
bspc rule -a "zoom " state=floating
bspc rule -a "vmware-view" state=floating
bspc rule -a "Vmware-view" state=floating
bspc rule -a "Shutter" state=floating
bspc rule -a "invoiceninja" state=tiled
bspc rule -a "Invoiceninja" state=tiled
bspc rule -a "Invoice_Ninja" state=tiled
bspc rule -a "Thunar" state=floating
