#! /bin/zsh
# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# if on the laptop
if [ "$HOST" = "sam-void" ] || [ "$HOST" = "sam-lap" ]
then
	bspc monitor eDP1 -d 1 2 3 4 7 8 9 0
	polybar laptop &
	bspc config top_padding 30
else
	echo "$HOST"
	# set up multi-monitor
	# (have to change this in order to use with polybar)
	#bspc monitor %DP-2.8 -n bottom
	bspc monitor DisplayPort-2 -n bottom
	#bspc monitor DP-5 -n top

	bspc monitor bottom -d 1 2 3 4
	bspc monitor DisplayPort-0 -d 7 8 9 0

	# start polybars
	polybar bottom & 
	polybar top & 

	# padding for polybar
	bspc config -m bottom top_padding 30
	bspc config -m DisplayPort-0 top_padding 30
fi

# floating window rules
bspc rule -a zoom state=floating
bspc rule -a "zoom " state=floating
bspc rule -a "vmware-view" state=floating
bspc rule -a "Vmware-view" state=floating

bspc rule -a "Shutter" state=floating
