[[language]]
name = "python"
auto-format = true

# introduce new langauge for buffer & snippets
[language-server.scls]
command = "simple-completion-language-server"

[language-server.omnisharp]
command = "omnisharp"
args = [ "--languageserver" ]

[language-server.scls.config]
max_completion_items = 20
snippets_first = true
feature_words = true
feature_snippets = true
feature_unicode_input = true
feature_paths = true

[[language]]
name = "make"
language-servers = [ "scls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]
